{% set name = "securesystemslib" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/securesystemslib-{{ version }}.tar.gz
  sha256: a27e519247576f2a77b97fb03267d8eeb88eba715d12da64109e845616f919c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - securesystemslib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/secure-systems-lab/securesystemslib
  license: MIT AND CC0-1.0
  license_file:
    - LICENSE
    - securesystemslib/_vendor/ed25519/LICENSE
  summary: A library that provides cryptographic and general-purpose routines for Secure Systems Lab projects at NYU

extra:
  recipe-maintainers:
    - kenodegard
