{% set name = "securesystemslib" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/securesystemslib-{{ version }}.tar.gz
  sha256: 4b8d00abd93707ead10b69eb2b8582376a1364de3b0a71077de534c2ef4985e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - securesystemslib
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/secure-systems-lab/securesystemslib
  license: MIT AND CC0-1.0
  license_file:
    - LICENSE
    - securesystemslib/_vendor/ed25519/LICENSE
  summary: A library that provides cryptographic and general-purpose routines for Secure Systems Lab projects at NYU

extra:
  recipe-maintainers:
    - kenodegard
